export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  FAMILY_ALREADY_EXISTS: 'FAMILY_ALREADY_EXISTS',
  FAMILY_NOT_FOUND: 'FAMILY_NOT_FOUND',
  FAMILY_MEMBER_NOT_FOUND: 'FAMILY_MEMBER_NOT_FOUND',
  FAMILY_MEMBER_LIMIT_EXCEEDED: 'FAMILY_MEMBER_LIMIT_EXCEEDED',
  RESTRICTION_MEMBER_NOT_FOUND: 'RESTRICTION_MEMBER_NOT_FOUND',
  RESTRICTION_DUPLICATE: 'RESTRICTION_DUPLICATE',
  PREFERENCE_FAMILY_NOT_FOUND: 'PREFERENCE_FAMILY_NOT_FOUND',
  PREFERENCE_NOT_FOUND: 'PREFERENCE_NOT_FOUND',
  RECIPE_NOT_FOUND: 'RECIPE_NOT_FOUND',
  RECIPE_NOT_OWNER: 'RECIPE_NOT_OWNER',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export class AppError extends Error {
  public readonly statusCode: number;
  public readonly code: ErrorCode;
  public readonly details?: unknown;

  constructor(message: string, statusCode: number, code: ErrorCode, details?: unknown) {
    super(message);
    this.name = 'AppError';
    this.statusCode = statusCode;
    this.code = code;
    this.details = details;
  }
}
